### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by NekoIriyaRu** [test123456654321/LunaHook#1]
Wtf? What happened? I found this repository through a video on Bilibili.
For what reason were the old repositories deleted?

**Comment by test123456654321** [comment]
not deleted... my account was blocked for unknown reasons....

https://lunatranslator.xyz/posts/1809800410869792768

**Comment by NekoIriyaRu** [comment]
> not deleted... my account was blocked for unknown reasons....
> 
> https://lunatranslator.xyz/posts/1809800410869792768

How can your website be translated into Russian?

**Comment by test123456654321** [comment]
https://github.com/HIllya51 can access now ~
