### ISSUE TITLE
多余文本

### ISSUE THREAD

**Issue by qscasdasd** [test123456654321/LunaHook#2]
### vndb link/id

https://vndb.org/v6187

### Game resource 游戏资源

https://zi0.cc/d/%60%E3%80%90%E5%90%88%E9%9B%86%E7%B3%BB%E5%88%97%E3%80%91/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86/%E6%B5%AE%E5%A3%AB%E5%BE%B7galgame%E6%B8%B8%E6%88%8F%E5%90%88%E9%9B%86-4/2008%E5%B9%B410%E6%9C%88/2008%E5%B9%B410%E6%9C%88/%5B081024%5D%5BTAKE%20OUT%5D%20%E3%81%BF%E3%81%A1%E3%81%8F%E3%81%95%20%EF%BD%9ELoitering%20on%20the%20way%EF%BD%9E%20%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E7%89%88%20(bin%2Bcue).rar?sign=ntf7Djockv4Sbl5heP_CML0Tfn8ixl-l1gaI-WDwoWo=:0

### screenshot 截图

![1](https://github.com/test123456654321/LunaHook/assets/167575533/24506d5c-4fd0-4d2b-a696-b0de3c78e720)
文本超过一行的话，第二行的文本会多余的再次显示在末尾。复现的话进新游戏点几下就行

**Comment by test123456654321** [comment]
https://github.com/test123456654321/LunaHook/commit/34edb1bfabc55e43676553007285b5bda4b9566c
